# Use root/example as user/password credentials
version: '3.9'
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"  
    # With environments variables  
    # env_file: .env
    environment:
      MONGO_INITDB_DATABASE: "${DATABASE}"
      MONGO_INITDB_ROOT_USERNAME: "${ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${ROOT_PASSWORD}"